### ISSUE TITLE
Update the readme 

### ISSUE THREAD

**Issue by ljcnz** [SE701Group3/git-brunching#1]
**Describe the change requested**
The read me needs to be updated to provide more information to contributors and people who view the repo

-How to setup backend and frontend

**Comment by jacoballen4534** [comment]
Added backend readme via #29. Re-using this issue for frontend.

**Comment by itsercleung** [comment]
@ljcnz Could you update the root readme to include small detail about Git brunching, and a small note to say checkout wiki for setup guides or something similar?
