### ISSUE TITLE
Fix the typo in the pull request template

### ISSUE THREAD

**Issue by ljcnz** [SE701Group3/git-brunching#118]
**Describe the change requested**
A mission-critical error was made that has severely undercut performance.

"nessisary" needs to be changed to "necessary" in .github/pull_request_template.md

**Comment by merw957** [comment]
While you're at it (whoever fixes this), change "atleast" to "at least" in the last acceptance criteria. 🤔

**Comment by ljcnz** [comment]
> While you're at it (whoever fixes this), change "atleast" to "at least" in the last acceptance criteria. 🤔

Whoever wrote this template should really invest in grammarly...
