### ISSUE TITLE
Update Swagger Docs apart from user

### ISSUE THREAD

**Issue by itsercleung** [SE701Group3/git-brunching#124]
**User Story:**
As a developer, I want to be able to understand all api functions clearly, so I can further expand upon the functions in the future

**Acceptance Criteria:**
- [ ] Reservation functions updated for swagger docs
- [ ] Restaurant functions updated for swagger docs

**Additional Context:**
N/A

**Comment by nidhineshnand** [comment]
@gracecocks  @MingChen91  Thanks for your help for generating these docs
