### ISSUE TITLE
Read and setup git-brunching project

### ISSUE THREAD

**Issue by itsercleung** [SE701Group3/git-brunching#146]
**Describe the change requested**
When passing the project to the next group, we need to make sure that the documentation and github repo is concise and easy to read. 

Please, run through Github to see if you can setup the frontend, backend, database, and provide feedback on what difficulties you have found and overall results. 

Comment your findings here. They DON'T need to be long. 

Thank you

**Comment by jacoballen4534** [comment]
#### Frontend
- There are a few npm commands in package.json that are not documented, eg `build`, `test`, `eject`.  
#### Testing
- No readme. 
- I couldn't get any of the cypress tests to pass. Tried Chrome and Firefox.
- Instructions do not mention running the backend.

#### Development-Environment Wiki
- Can probably rip the backend test instruction and put it into 'Setting up and running the Backend 
Testing Suite'

**Comment by ljcnz** [comment]
#### Development-Environment Wiki
- Can probably rip the backend test instruction and put it into 'Setting up and running the Backend 
Testing Suite'

Do you think it needs its own page? Or can it just go into https://github.com/SE701Group3/git-brunching/wiki/Working-on-your-Development-Environment

**Comment by ahmadumar020** [comment]
## Setting up the Database

1.	Unclear about "Add the IPv4 address of the machine that is running the /backend directory to the authorization whitelist (Authorization -> Add network)." 

2.	In regards to creating the .env file, we didn't put the env variables into the github for security reasons.

**Comment by ljcnz** [comment]
> ## Setting up the Database
> 1. Unclear about "Add the IPv4 address of the machine that is running the /backend directory to the authorization whitelist (Authorization -> Add network)."
> 2. In regards to creating the .env file, we didn't put the env variables into the github for security reasons.

@1, ill change that, @2, you create .env on your local so you can connect to the db. its .gitignored so you don't commit it
