### ISSUE TITLE
Update Frontend high level architecture page in wiki

### ISSUE THREAD

**Issue by itsercleung** [SE701Group3/git-brunching#147]
**User Story:**
As a developer, I want to be able to read about the frontend architecture to get an overview of what is being used in the frontend. This is so I can roughly understand how the frontend works. 

**Acceptance Criteria:**
* [ ] Update of frontend high level architecture page 

**Additional Context:**
N/A

**Comment by gracecocks** [comment]
Updated [here](https://github.com/SE701Group3/git-brunching/wiki/Product-Overview)
