### ISSUE TITLE
Create GET booking api function 

### ISSUE THREAD

**Issue by itsercleung** [SE701Group3/git-brunching#19]
**User Story:**
* As a user, I want to be able to view my successful booking, so I can recheck what time and other details I have made during the booking. 

**Acceptance Criteria:**
- [ ] Create api function - Get the booking entry from the unique booking ID
- [ ] Create unit tests to cover both api functions
- [ ] Comment your code appropriately - follow code comment conventions over [here](https://github.com/SE701Group3/git-brunching/wiki/Coding-Conventions)

**Additional Context:**
N/A

**Comment by gracecocks** [comment]
@jacoballen4534 also a contributor.
