### ISSUE TITLE
Create post update booking api function 

### ISSUE THREAD

**Issue by itsercleung** [SE701Group3/git-brunching#21]
**User Story:**
* As a user, I want to be able to change my successful booking (unless 1 hour before booking time), so that I can post-pone my booking and/or change details such as my mobile number in case something changes in the future.

**Acceptance Criteria:**
- [ ] Create api function - Update the booking entry given the unique booking ID and new changes requested (i.e. can change to another available time, booker's name, phone, email) - from the booking table in our database. 
- [ ] Create unit tests to cover both api functions
- [ ] Comment your code appropriately - follow code comment conventions over [here](https://github.com/SE701Group3/git-brunching/wiki/Coding-Conventions)

**Additional Context:**
N/A

**Comment by jacoballen4534** [comment]
Should we use Patch instead of Post?

**Comment by ljcnz** [comment]
> Should we use Patch instead of Post?

Use either Patch or Put for an update api yeah. 

I did some googling and it seems that PUT requests normally contain the entire entity body (ie; if you want to update a users first name, you still send the users last name, d.o.b, etc even if they haven't changed)

Patch requests typically get used for "patching" a single part of an entity. ie; you PATCH { "firstname" : "Liam2" } and that's all you send.

As this is an implementation detail, I'm fine with you guys deciding what to do. Just write about your choice in the PR if you want :)
