### ISSUE TITLE
Create submit booking api function

### ISSUE THREAD

**Issue by itsercleung** [SE701Group3/git-brunching#23]
**User Story:**
* As a user, I want to be able to submit a booking for the selected restaurant and time, so that I can save a table in the future for one of my favourite restaurants 

**Acceptance Criteria:**
- [ ] Create api function - Create a booking entry which is assigned to the specific restaurant and reservation time
- [ ] Create unit tests to cover both api functions
- [ ] Comment your code appropriately - follow code comment conventions over [here](https://github.com/SE701Group3/git-brunching/wiki/Coding-Conventions)

**Additional Context:**
N/A

**Comment by gracecocks** [comment]
@gracecocks also a contributor
