### ISSUE TITLE
Create post and update user api functions

### ISSUE THREAD

**Issue by itsercleung** [SE701Group3/git-brunching#24]
**User Story:**
As a user, I want to be able to add my user details (including my full name, email, mobile number) to the restaurant booking that I made, so that I can identify myself when I go in for the reservation. 

**Acceptance Criteria:**
- [ ] Create api function - Create a user entry given user details and place into the database (user table)
- [ ] Create api function - Update a user entry given the unique booking identifier (from the user table)
- [ ] Create unit tests to cover both api functions
- [ ] Comment your code appropriately - follow code comment conventions over [here](https://github.com/SE701Group3/git-brunching/wiki/Coding-Conventions)

**Additional Context:**
N/A

**Comment by gracecocks** [comment]
@MingChen91 also a contributor.
