### ISSUE TITLE
Add a "Setting up your environment" page to the wiki

### ISSUE THREAD

**Issue by ljcnz** [SE701Group3/git-brunching#30]
**Describe the change requested**
As part of the initialization of the frontend and backend projects, two README.md files were created (one in each directory) that specify how to start development on the respective module. It would be helpful to have the information contained in those readmes be displayed on the wiki as well, so the wiki becomes a full start->finish guide on development.

**Comment by ljcnz** [comment]
I've created a page but @jacoballen4534 is currently revamping the backend instructions, so this issue is temporarily blocked by #51

**Comment by jacoballen4534** [comment]
> I've created a page but @jacoballen4534 is currently revamping the backend instructions, so this issue is temporarily blocked by #51

This has been updated.

**Comment by ljcnz** [comment]
New page can be seen here
https://github.com/SE701Group3/git-brunching/wiki/Setting-up-and-working-on-your-development-environment
