### ISSUE TITLE
Create a booking time selection section

### ISSUE THREAD

**Issue by mmir415** [SE701Group3/git-brunching#34]
**User Story:**

As a front-end feature, I have been assigned to work on the Times section of the Booking process that the restaurants will be getting used for. Will follow on from the Guests and Date section of the Booking process that George will be working on.

**Acceptance Criteria:**

* A/C
 If Booking times can be clicked on and sent off as part of the booking, and if certain times can be greyed out if they are unavailable.

**Additional Context:**
 Linked to Bookings-Guests and Date.

**Comment by mmir415** [comment]
@Sabatr

**Comment by Sabatr** [comment]
Some possible things to think about:

- Loading on the times when calling an API
- Layout of the times
- Styling of times when they have been clicked

-
