### ISSUE TITLE
Create a page to select dates and number of people for a booking

### ISSUE THREAD

**Issue by George-E-M** [SE701Group3/git-brunching#41]
**User Story:**

As a user I want to be able to select a date and number of people to book for so I can makes sure the table I get has enough seats and is booked for the right day.

**Acceptance Criteria:**

* The page fits the style of the overall application
* The page allows the user to select a date and number of seats to book
* The page leads into the next stage of the booking, selecting the time

**Additional Context:**

**Comment by George-E-M** [comment]
@Sabatr

**Comment by Sabatr** [comment]
Looks good.  I was messing around with Redux and used the seats stuff as an example. It works, but it hasn't been merged or anything yet so keep that in mind.
