### ISSUE TITLE
Address security alert

### ISSUE THREAD

**Issue by jacoballen4534** [SE701Group3/git-brunching#52]
**Describe the change requested**
Github has provided a security alert for one of our dependencies (minimist).
This should be updated.

**Comment by ljcnz** [comment]
Looks like version 1.2.5 of minimist is free of vulnerabilities, @jacoballen4534 are you able to quickly update and verify nothing has broken?

**Comment by ljcnz** [comment]
Even though I've got an issue open I'm going to quickly do this one as it's a semi-urgent one
