### ISSUE TITLE
Convert database ids to varchar

### ISSUE THREAD

**Issue by jacoballen4534** [SE701Group3/git-brunching#59]
**Describe the change requested**
Due to the possibility of duplicate keys when generating a random number, the reservation id column could be changed to varchar, then use a package such as [uuid](https://www.npmjs.com/package/uniqid) or [shortid](https://www.npmjs.com/package/shortid) to generate unique ids.

**Comment by itsercleung** [comment]
@jacoballen4534 You are free to start it - William and Ming have access to Cloud SQL

**Comment by jacoballen4534** [comment]
> @jacoballen4534 You are free to start it - William and Ming have access to Cloud SQL
I am unsure how to change the type, as it is a foreign key constraint for other tables, so will not allow just modifying the type. @wshin387  do you know how to do it?
I can update the reservation endpoint after.

**Comment by MingChen91** [comment]
> > @jacoballen4534 You are free to start it - William and Ming have access to Cloud SQL
> 
> I am unsure how to change the type, as it is a foreign key constraint for other tables, so will not allow just modifying the type. @wshin387 do you know how to do it?
> I can update the reservation endpoint after.

Miles knows how to do this actually. You have to lock the table, drop the foreign key constraint, then change the type, and add the foreign key back again. @merw957 has some sample sql code

**Comment by merw957** [comment]
> > > @jacoballen4534 You are free to start it - William and Ming have access to Cloud SQL
> > 
> > 
> > I am unsure how to change the type, as it is a foreign key constraint for other tables, so will not allow just modifying the type. @wshin387 do you know how to do it?
> > I can update the reservation endpoint after.
> 
> Miles knows how to do this actually. You have to lock the table, drop the foreign key constraint, then change the type, and add the foreign key back again. @merw957 has some sample sql code

This is the SQL code I used. I was changing the user's ID to auto incrementing, which couldn't be done without removing it as a foreign key from the reservation table:

`LOCK TABLES 
    RESERVATION WRITE,
    USER WRITE;

ALTER TABLE RESERVATION
    DROP FOREIGN KEY Reservation_User,
    MODIFY UserID INT(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE USER MODIFY ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT;

ALTER TABLE RESERVATION
    ADD CONSTRAINT Reservation_User FOREIGN KEY (UserID)
          REFERENCES USER (ID);

UNLOCK TABLES;`

Hope it helps.

**Comment by MingChen91** [comment]
Changed the DB to use varchar(45) instead of int(11) now. Closing.
