### ISSUE TITLE
Add Front End Architecture to Wiki

### ISSUE THREAD

**Issue by gracecocks** [SE701Group3/git-brunching#7]
**Describe the change requested**
The wiki needs pages describing the architecture for each component in the Front End. This should include but is not limited to:

- Landing Page
- Booking Page
- Ordering Page

**Comment by mmir415** [comment]
At the moment, the Wiki has the general concepts for each page as per the initial meeting. These have since changed, so I'll redo the Wiki pages accordingly as per the new design. Should I only be closing this issue when all content for the Front-end writeup is done and dusted?

**Comment by gracecocks** [comment]
Yes, please update the pages regularly as the design changes. However, once a first revision of these pages has been completed to outline the current design the issue may be closed.

**Comment by mmir415** [comment]
Completed. As it was decided that we weren't doing Ordering for the moment, changed all the pages for the new design and added links to the paper layouts currently in the Google Drive for each page.
