### ISSUE TITLE
Remove .DS_Store from the repo

### ISSUE THREAD

**Issue by ljcnz** [SE701Group3/git-brunching#79]
**Describe the change requested**
.DS_Store was added in with a random commit, need to remove it and potentially have a look into adding a top level .gitignore?

**Comment by ljcnz** [comment]
@Sabatr i remember you asking about a top level .gitignore, think we still need it?

**Comment by ljcnz** [comment]
@kkim534 just in the future be careful of this ^^

**Comment by Sabatr** [comment]
oh man, maybe we do need a top level one just in case,
