### ISSUE TITLE
Create API function - get all bookings for a restaurant 

### ISSUE THREAD

**Issue by itsercleung** [SE701Group3/git-brunching#81]
**User Story:**
As a restaurant manager, I want to be able to view all bookings so that I can make decisions on how much staff I need.

**Acceptance Criteria:**

* [ ] Created a function that gets all available booking information for a restaurant. 

**Additional Context:**
Will need a way to delete bookings automatically after booking date/time has been surpassed

**Comment by ljcnz** [comment]
Closing this issue as it will be addressed in #109
