### ISSUE TITLE
Revise the high level architecture page

### ISSUE THREAD

**Issue by ljcnz** [SE701Group3/git-brunching#85]
**Describe the change requested**
https://github.com/SE701Group3/git-brunching/wiki/High-Level-Architecture is outdated as we moved away from cloud functions towards a fe->be-> database architecture.

**Comment by gracecocks** [comment]
High Level Architecture and Database Schema pages were merged [here](https://github.com/SE701Group3/git-brunching/wiki/High-Level-Architecture-&-Database-Schema). 

This was due to conflicting information existing on both
