### ISSUE TITLE
Create a quick-init sql script to set up sql tables/exmaple data.

### ISSUE THREAD

**Issue by ljcnz** [SE701Group3/git-brunching#86]
**Describe the change requested**
When incoming devs are wanting to create their own development database, they will most likely want a script to run that quickly sets up their mysql instance with all necessary  tables & some example data.
This would streamline the contribution process significantly.

**Comment by ljcnz** [comment]
@wshin387 I don't suppose you kept a log of the commands you used?

**Comment by MingChen91** [comment]
> @wshin387 I don't suppose you kept a log of the commands you used?

You can export the schema using MySql workbench. I can set this up. I'll find you in person to discuss where you think we should document this

**Comment by MingChen91** [comment]
@ljcnz I'll set up the script for getting setting up a DB, with some example restaurants and opening hours. So when the next group takes over they'll have a set of restaurants to work with.

**Comment by MingChen91** [comment]
Included a script in <Development Environment> wiki page
